### ISSUE TITLE
segfault in seissol::dr::output::ElementWiseBuilder::initReceiverLocations()

### ISSUE THREAD

**Issue by NicoSchlw** [SeisSol/SeisSol#1046]
**Describe the bug**
Segmentation fault error during initialization (probably in seissol::dr::output::ElementWiseBuilder::initReceiverLocations())

**Expected behavior**
No error.

**To Reproduce**
1. Which version do you use? nico/2nuc-latest-master 10ae92ee3bb4a90931e37ee2cef5966ab92c785a
2. Which build settings do you use? Which compiler version do you use? SeisSol_Release_dskx_6_viscoelastic2, intel spack build on Frontera 
3. On which machine does your problem occur? If on a cluster: Which modules are loaded? /work2/09160/ulrich/frontera/spack/share/spack/modules/linux-centos7-cascadelake
4. Provide parameter/material files.

[parameters.txt](https://github.com/SeisSol/SeisSol/files/14209937/parameters.txt)
[6100231.txt](https://github.com/SeisSol/SeisSol/files/14209938/6100231.txt)

**Comment by sebwolf-de** [comment]
Can you run the setup with a debug build? Then you'd see which line causes the segfault. Additionally, some assertion might fail earlier, which gives us a hint.

**Comment by sebwolf-de** [comment]
I can confirm the error. You did not specify `refinement_strategy` in `&Elementwise`. The default value is then to use no fault refinement, which does not work.
Possible workaround: Use `refinement_strategy = 1`.
Possible fix: Implement a NoneRefiner here: https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/Output/FaultRefiner/FaultRefiners.hpp, otherwise, we return a nullptr here: https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/Output/FaultRefiner/FaultRefiners.cpp#L30-L32

**Comment by davschneller** [comment]
Ok; but that should have been caught previously, should it? I.e. was the `castToRefinerType` method used in some previous version? Otherwise, maybe it's good to insert a `logError` in https://github.com/SeisSol/SeisSol/blob/5f05d19847dd07839c313857699cdba7a4ddcf54/src/DynamicRupture/Output/FaultRefiner/FaultRefiners.cpp#L30-L32 ?

Also, the `NoneRefiner` (or `NullRefiner`?) sounds like a good idea to me.

**Comment by sebwolf-de** [comment]
I don't use the `castToRefinerType` anymore after #1004, but directly cast it to the enum in the parameter reader.
I'd vote for the NoneRefiner.
