### ISSUE TITLE
on compiling the program

### ISSUE THREAD

**Issue by anetskorkina** [SeisSol/SeisSol#259]
First of all, we worried about the netcdf installation issue. Please, see some terminal output in the attachments. We have tried to solve this issue for a long time, but the same error comes again and again with linking hdf5 library. Package hdf5 was successfully configured and installed according to the guide.
We use fedora linux platform, 64 bit, version 32. All of the necessary environmental variables like "PATH", "LD_LIBRARY_PATH","CPPFLAGS","LDFLAGS" have been checked. All of the necessary compilers
like mpif90, mpicc, h5pcc, gcc and gfrotran are seen for command "which". We even tried the link below to fix it, but the same error appears. For more detailed info, the configure.log is attached.
https://gist.github.com/milancurcic/3a6c1a97a99d291f88cc61dae6621bdf
We are sorry if the described above problem is common, but we stuck here. We also would like to ask if there is a light-weighted linux distribution file, for instance with "iso" extension,  with pre-installed linux packages required for SeisSol parallel execution?
If yes, could you please provide the link to download it? This would help a lot.
![term](https://user-images.githubusercontent.com/41052565/96338326-d8e52700-1095-11eb-80ff-7da5f2078238.jpg)
![netcdf](https://user-images.githubusercontent.com/41052565/96338328-da165400-1095-11eb-81e3-3ba362b1b77d.jpg)
[config.log](https://github.com/SeisSol/SeisSol/files/5395754/config.log)

**Comment by ravil-mobile** [comment]
> We also would like to ask if there is a light-weighted linux distribution file, for instance with "iso" extension, with pre-installed linux packages required for SeisSol parallel execution?

There are a few experimental Docker images on dockerhub. You can see an example below.
```
$ cat ./Dockerfile
FROM ravilmobile/seissol-env:ubuntu-18.04_skylake_gcc-8.3.0_openmpi-3.1.5

ARG UID=1000
ARG GID=1000

RUN addgroup --gid $GID seissol
RUN adduser --disabled-password --gecos '' --uid $UID --gid $GID user
RUN chown $UID:$GID /local_workspace
USER user

$ docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) --tag seissol-env .
$ docker run --rm -it seissol-env
```
Just create a Dockerfile as it is shown in the example, build and run it. You can inspect all packages which are needed at compile- and run-time of SeisSol in */opt/view* inside of the resultant image.

**Comment by uphoffc** [comment]
The issue seems to be that MPI is not found:
```
configure:13695: gcc -o conftest  -I/usr//include -I/root/include -L/usr/lib -L/root/lib conftest.c -lhdf5  -lm -lz  >&5
/usr/bin/ld: /root/lib/libhdf5.a(H5Fsuper.o): in function `H5F__super_read':
H5Fsuper.c:(.text+0x2949): undefined reference to `ompi_mpi_comm_null'
/usr/bin/ld: H5Fsuper.c:(.text+0x2965): undefined reference to `ompi_mpi_byte'
/usr/bin/ld: H5Fsuper.c:(.text+0x2977): undefined reference to `MPI_Bcast'
```

What is the output of "h5pcc -show"? Does it begin with mpi... ?

**Comment by AlexV321** [comment]
Dear ravil-mobile and uphoffc,

Thank you for your feedback. I will save and keep this link as help for future work.

Here is output of "h5pcc -show" command
![h5pcc_show](https://user-images.githubusercontent.com/73217115/96686527-4ee3d980-1387-11eb-87da-025836b4cf52.jpg)

While configuring netcdf in my "HOME" directory i noticed that there is no reaction if i adjusted my env variables as "CC=h5pcc",but when i used "export CC=h5pcc" it became a right way, since now i can see h5pcc in the config.log instead of the default compiler "gcc" and the errors have been occured before now absent. 

![config_log](https://user-images.githubusercontent.com/73217115/96684838-e98ee900-1384-11eb-8ba8-d2d5c9705c25.jpg)
![netcdf_config](https://user-images.githubusercontent.com/73217115/96684877-fa3f5f00-1384-11eb-9d49-0a5db923f683.jpg)

Afterwards, continue installing SeisSol, only issue #100 appears and finally with some warnings i got this 
![seissol_build](https://user-images.githubusercontent.com/73217115/96685827-55258600-1386-11eb-96fc-217c6aea5892.jpg)

**Comment by uphoffc** [comment]
Ok, great! Yes, you need export otherwise the scope of setting CC is limited to the current command. I.e. either

CC=h5pcc ./configure ...

or

export CC=h5pcc
./configure ...
