### ISSUE TITLE
Compiling SeisSol for Intel Xeon Phi KNL

### ISSUE THREAD

**Issue by gmocornejos** [SeisSol/SeisSol#32]
Hello! 

I'm trying to compile SeisSol for Intel Xeon Phi knl. I followed the [wiki instructions](https://github.com/SeisSol/SeisSol/wiki/Compilation) until step E, the following are variables in _build/options/supermuc_mac_cluster.py_ : 

    # build options
    compileMode                 = 'release'
    parallelization             = 'hybrid'
    generatedKernels            = 'yes'
    measureNodeLevelPerformance = 'none'
    useExecutionEnvironment     = 'yes'
    logLevel                    = 'warning'
    logLevel0                   = 'info'
    # machine dependent options (SNB-EP, Bulldozer)
    arch = 'dknl'
    # new variables
    order     = '$ORDER'
    netcdf    = 'yes'
    netcdfDif = '$HOME'
    hdf5      = 'yes'
    hdf5Dir   = '$HOME'

When I try to compile using `scons -j 32 buildVariablesFile=build/options/supermuc_mac_cluster.py`, I get this error message:

    scons: Reading SConscript files ...
    ********************************************
    ** Welcome to the build script of SeisSol **
    ********************************************
    Copyright (c) 2012-2016, SeisSol Group
    
    scons: *** Invalid value for option order: .  Valid values are: ('none', '2', '3', '4', '5', '6', '7', '8')
    File "/home/gmocornejos/SeisSol/SConstruct", line 216, in <module>

Thanks for your help, 

-- Guillermo.

**Comment by swollherr** [comment]
Hi Guillermo,

please substitute all $... variables according to what you need. I.e.:
- choose a convergence order between 2 and 8 (order of accuracy for the wave propagation part) instead of $ORDER. For typical production runs we use order 4-6, for testing order 3 is also fine.
- choose your target architecture for $ARCH. In your case arch = 'knl' for Knight Landing (Xeon Phi).
- if netcdf and hdf5Dir is not installed in your home directory (see steps C and D) change $HOME to the path where it's installed.

Stephanie

**Comment by gmocornejos** [comment]
Hi Stephanie,

With your recommendations, I was able to start the compilation. I have problems linking with curl lib, but that is another story. 

Thank you! 

-- Guillermo.
