### ISSUE TITLE
Make CI pipeline simulations complete

### ISSUE THREAD

**Issue by sebwolf-de** [SeisSol/SeisSol#938]
The CI pipeline should check all material models / friction laws in SeisSol.

### Rationale

E.g. plasticity is currently not checked, which lead to problems like this: https://github.com/SeisSol/SeisSol/pull/916/files

### Description

Add an automatic benchmark test for

- [x] #944
- [x] Plasticity
- [x] Anisotropy

### Additional information
Are there any other models, which we do not check? Currently, the CI checks the following friction laws:
* Linear Slip Weakening
* Aging Law
* Slip Law
* Fast Velocity Weakening Law
* Thermal Pressurization
* Imposed Slip Rate

and the following material models
* elastic
* poroelastic

**Comment by davschneller** [comment]
Two/three things to add would be that are currently on my mind:

* plasticity and _maybe_ anisotropy can also be enabled for GPU builds. (because of #916; for CPUs we additionally had #890)
* we may also need to run all the test cases with MPI instead of OpenMP (due to e.g. #903)
* test a non-zero initial condition once, if that's not done already. Maybe convergence tests on CPU as well?

**Comment by sebwolf-de** [comment]
* Yes, we can add these models to the GPU pipeline.
* Yes, would be good to do that. How many cores has the runner? If there are sufficiently many, we can use two mpi ranks on one node.
* tpv-poro does that/will do that.

**Comment by davschneller** [comment]
Currently, it has 8 cores associated to it. However we could, for just testing the MPI things, make each process single-threaded.
