### ISSUE TITLE
Recent changes break viscoelastic2

### ISSUE THREAD

**Issue by sebwolf-de** [SeisSol/SeisSol#939]
**Describe the bug**
Viscoelastic2 in single precision results in `Inf/NaN` error. Double precision works well.

**Expected behavior**
Viscoelastic2 should not result in an `Inf/Nan` error, when using single precision.

**To Reproduce**
1. Master branch (7fde47786f10ae)
2. gcc, viscoelastic2, single precision build
3. local
4. https://github.com/SeisSol/precomputed-seissol/tree/sebastian/more-ci/tpv5-visco

**Screenshots/Console output**
Slice through x==0, in the middle you see the correct solution, towards the boundaries you see numerical artifacts.
![image](https://github.com/SeisSol/SeisSol/assets/24592027/1bb7c81e-5681-47c1-836c-21aa36396851)

**Additional context**
It works with `v1.0.1`

**Comment by sebwolf-de** [comment]
Double precision is also affected: https://gitlab.lrz.de/ci_seissol/SeisSol/-/jobs/6598427

**Comment by sebwolf-de** [comment]
GTS still works, only LTS is affected.

**Comment by davschneller** [comment]
Found it, most likely. The problem is that the maximum timestep was not automatically restricted anymore, as it was done in the old version. I overlooked some part in the `readpar.f90` file during the FORTRAN removal in #829 , namely

https://github.com/SeisSol/SeisSol/blob/9b1b0ec970af4ad79a155c63035234b660838476/src/Reader/readpar.f90#L2233-L2244

For example: for the unit tests in the https://github.com/SeisSol/SeisSol/tree/sebastian/more-ci branch, if we were to add `fixtimestep=0.01`, it should work again.

Shall we add the timestep restriction again to the code? I.e. if no maximum timestep is specified, set the maximum timestep to what's given in the documentation, as written in https://seissol.readthedocs.io/en/latest/attenuation.html .

**Comment by sebwolf-de** [comment]
That sounds reasonable. Please add the warning again.
The documentation says: ` This is done by default by SeisSol when attenuation is turned on, and the parameter FixTimeStep of the the &Discretization namelist (main parameter file) is not set.`, but currently, nothing is done.
