### ISSUE TITLE
Viscoelastic simulations crashing with point source and 3d variable attenuation

### ISSUE THREAD

**Issue by jrekoske** [SeisSol/SeisSol#957]
**Describe the bug**
I have crashes when I run `viscoelastic2` simulations using type 50 point sources, and 3D-variable viscoelastic attenuation. I have checked previous issues and saw that #293 had a similar issue that was fixed by clearing the cmake cache. I have tried this but it does not fix my issue. The error also does not occur when using constant material properties, or when using elastic simulations.

**To Reproduce**
I used the commit `6aecb20ba05b8fa1565e5171d335e93fb12d67ab` and used the build settings

`cmake -DCOMMTHREAD=ON -DNUMA_AWARE_PINNING=ON -DASAGI=ON -DCMAKE_BUILD_TYPE=Release -DHOST_ARCH=skx -DPRECISION=double -DORDER=4 -DGEMM_TOOLS_LIST=LIBXSMM,PSpaMM -DEQUATIONS=viscoelastic2 -DNUMBER_OF_MECHANISMS=3 ..` and the gcc compiler

All my simulation setup files (parameter, mesh, source, receiver and material files) are on supermuc at `/hppfs/scratch/0B/di46bak/issue`, I can provide here if needed or produce a simpler example.

My simulations are crashing when I use 16 nodes on the test partition. I attached the output file and the error file just contains: `double free or corruption (!prev)`

[out.txt](https://github.com/SeisSol/SeisSol/files/12667552/out.txt)

**Comment by jrekoske** [comment]
[issue.zip](https://github.com/SeisSol/SeisSol/files/12667619/issue.zip) simulation input attached here

**Comment by Thomas-Ulrich** [comment]
I would first try removeing the line
` FixTimeStep = 0.05                  ! Manually chosen maximum time step`
And decreasing CFL to 0.4.

**Comment by sebwolf-de** [comment]
Hi John, I can reproduce the bug. It would be great if you could provide a mesh with ~100k elements which has the same problem for easier debugging.

**Comment by davschneller** [comment]
Looking through the log... I'd take the wild guess that it's related to the point sources and/or receiver implementation.

And indeed, there may be a bug with the point sources:

https://github.com/SeisSol/SeisSol/blob/6aecb20ba05b8fa1565e5171d335e93fb12d67ab/src/SourceTerm/Manager.cpp#L384

However, `NUMBER_OF_QUANTITIES` includes the mechanisms iirc (even for `viscoelastic2`), while the tensor dimension does not. I.e. it's too large for `viscoelastic2`.

It should be fixed by replacing the `NUMBER_OF_QUANTITIES` by `PointSources::TensorSize`.

**Comment by jrekoske** [comment]
Thanks this patch did the trick for me.

**Comment by krenzland** [comment]
Great!
